print(os.clock())
print(os.time())
print("\nDate: "..os.date())
print("Year: "..os.date("%Y"))
print("\nEnv: "..os.getenv("HOME"))
print("\nCreating a file: ", os.execute("touch lua"))
print("See the file created: ", os.execute("ls"))
print("\nRenaming the file called lua to lua_renamed: ", os.rename("lua", "lua_renamed"))
print("\nRemoving file: ", os.remove("lua_renamed"))
